name: Deployment
on:
  push:
    branches:
      - master
  schedule:
      - cron: "*/30 * * * *"
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Fetch data
      run: |
        cd backend
        pip install -e .
        python3 covid_vaccine_finder/main.py # Saves *.json files to frontend currently
    - name: Save data and last updated
      uses: actions/upload-artifact@v2
      with:
        name: vaccine-info
        path: |
          frontend/public/data.json
          frontend/public/last-updated.json
          frontend/public/feed.xml
  deploy:
    needs: fetch-data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download vaccine-info
      uses: actions/download-artifact@v2
      with:
        name: vaccine-info
        path: frontend/public/
    - name: Install Packages
      run: |
        cd frontend
        npm install
    - name: Build page
      run: |
        cd frontend
        npm run build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./frontend/build
