name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: |
        cd backend
        pip install -e .
        python3 covid_vaccine_finder/main.py
    - name: Save data and last updated
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          frontend/public/*.json
